#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run Prettier only on specific file types (md, json, ts, js)
npx prettier --write "$(git ls-files --exclude-standard '*.md' '*.json' '*.ts' '*.js')"

# Add any modified files to the commit
git add .

# Amend the commit with the formatted changes (without changing the commit message)
git commit --amend --no-edit
